### ISSUE TITLE
swe_set_ephe_path is not a function

### ISSUE THREAD

**Issue by heymartinadams** [mivion/swisseph#41]
I’m getting `Uncaught TypeError: _swisseph2.default.swe_set_ephe_path is not a function`... might you know why that could be?

**Comment by heymartinadams** [comment]
Installing the `swisseph` node module on another computer gave me this error:

```
error /Users/user/app/node_modules/swisseph: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/user/app/node_modules/swisseph
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@6.5.0 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/user/app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/user/app/node_modules/swisseph/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/user/app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/user/.node-gyp/6.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/user/.node-gyp/6.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/user/app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/user/app/node_modules/swisseph',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/swissephz/deps/swisseph/swecl.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/swedate.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/swehel.o
../deps/swisseph/swehel.c:3121:9: warning: comparison of array 'serr' not equal to a null pointer is always true [-Wtautological-pointer-compare]
    if (serr != NULL)
        ^~~~    ~~~~
1 warning generated.
  CC(target) Release/obj.target/swissephz/deps/swisseph/swehouse.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/swejpl.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/swemmoon.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/swemplan.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/sweph.o
../deps/swisseph/sweph.c:103:8: warning: missing field 'tid_acc' initializer [-Wmissing-field-initializers]
                            };
                            ^
1 warning generated.
  CC(target) Release/obj.target/swissephz/deps/swisseph/swephlib.o
  LIBTOOL-STATIC Release/swissephz.a
Usage: /usr/local/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
make: *** [Release/swissephz.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/app/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/user/.nvm/versions/node/v6.5.0/bin/node" "/Users/user/app/node_modules/swisseph/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/user/app/node_modules/swisseph
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
    at SpawnError (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/yarn/lib/errors.js:18:1)
    at ChildProcess.proc.on.code (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/yarn/lib/util/child.js:107:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by mivion** [comment]
It looks like some broken. Any help?

**Comment by heymartinadams** [comment]
Hi @mivion, I moved on from the codebase since then. I never found out what did or didn’t work (if it was on my end or this code). Thanks for getting back, though 👍
