### ISSUE TITLE
Error when installing swisseph with Meteor 1.8 and node v8.1.2

### ISSUE THREAD

**Issue by blissGitHub** [mivion/swisseph#58]
Hi
I'm using meteor 1.8
and node v8.1.2

When I run 

`meteor npm install --save swisseph `

I get the following error:

npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> swisseph@0.5.8 install /Users/bliss/Documents/Coder/ReactMeteor/new/node_modules/swisseph
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/bliss/anaconda/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/bliss/.meteor/packages/meteor-tool/.1.8.0.13gd4dz.15ig++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/bliss/.meteor/packages/meteor-tool/.1.8.0.13gd4dz.15ig++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bliss/Documents/Coder/ReactMeteor/new/node_modules/swisseph
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swisseph@0.5.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swisseph@0.5.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bliss/.npm/_logs/2018-11-03T15_33_53_276Z-debug.log

**Comment by blissGitHub** [comment]
Python version was pointing to a incompatible version.
I just changed python version using 

npm --python=/usr/bin/python2.6 install --save swisseph
