### ISSUE TITLE
swisseph.julday is not a function

### ISSUE THREAD

**Issue by Chirag-Chopraa** [mivion/swisseph#71]
I am getting this issue when I tried to run this example
[https://www.npmjs.com/package/swisseph#getting-sun-and-moon-position](url)

swisseph.julday(date.year, date.month, date.day, date.hour, swisseph.GREG_CAL, function (julday_ut) {
         ^

TypeError: swisseph.julday is not a function
    at Object.<anonymous> (/home/chirag/Desktop/backend_without_auth/index.js:41:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

![idd](https://user-images.githubusercontent.com/22336412/92298127-5845ed80-ef63-11ea-989f-aee671f4ec63.PNG)

**Comment by gkostov** [comment]
The example says `swisseph.swe_julday` and not `swisseph.julday` but you must have already found that out :)

**Comment by erikksuzuki** [comment]
I'm getting TypeError: swisseph.swe_julday is not a function having copied the same code from the README.MD
