### ISSUE TITLE
When I am deploying my node js application in which i have used this library on Aws EC2 or Render or Vercel, I am getting errors while running the server

### ISSUE THREAD

**Issue by Aditya-Poulima** [mivion/swisseph#87]
**DEPLOYING ON RENDER and VERCEL getting this  ERROR**

Oct 18 03:31:08 PM  node:internal/modules/cjs/loader:1340
Oct 18 03:31:08 PM    return process.dlopen(module, path.toNamespacedPath(filename));
Oct 18 03:31:08 PM                   ^
Oct 18 03:31:08 PM  
Oct 18 03:31:08 PM  Error: /opt/render/project/src/node_modules/swisseph/build/Release/swisseph.node: invalid ELF header
Oct 18 03:31:08 PM      at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
Oct 18 03:31:08 PM      at Module.load (node:internal/modules/cjs/loader:1119:32)
Oct 18 03:31:08 PM      at Module._load (node:internal/modules/cjs/loader:960:12)
Oct 18 03:31:08 PM      at Module.require (node:internal/modules/cjs/loader:1143:19)
Oct 18 03:31:08 PM      at require (node:internal/modules/cjs/helpers:119:18)
Oct 18 03:31:08 PM      at Object.<anonymous> (/opt/render/project/src/node_modules/swisseph/lib/swisseph.js:1:16)
Oct 18 03:31:08 PM      at Module._compile (node:internal/modules/cjs/loader:1256:14)
Oct 18 03:31:08 PM      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
Oct 18 03:31:08 PM      at Module.load (node:internal/modules/cjs/loader:1119:32)
Oct 18 03:31:08 PM      at Module._load (node:internal/modules/cjs/loader:960:12) {
Oct 18 03:31:08 PM    code: 'ERR_DLOPEN_FAILED'
Oct 18 03:31:08 PM  }
Oct 18 03:31:08 PM

**DEPLOYING ON CPANEL getting this ERROR**

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN lifecycle The node binary used for scripts is /home/poulkngb/nodevenv/moontimediary_backend/12/bin/node but npm is using /opt/alt/alt-nodejs12/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
make: execvp: cc: Permission denied
make: *** [Release/obj.target/swissephz/deps/swisseph/swecl.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/opt/alt/alt-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:314:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 2.6.32-954.3.5.lve1.4.86.el6.x86_64
gyp ERR! command "/opt/alt/alt-nodejs12/root/usr/bin/node" "/opt/alt/alt-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/poulkngb/nodevenv/moontimediary_backend/12/lib/node_modules/swisseph
gyp ERR! node -v v12.22.9
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN moontimediary@1.0.0 No description
npm WARN moontimediary@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swisseph@0.5.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swisseph@0.5.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/poulkngb/.npm/_logs/2023-10-18T12_36_09_574Z-debug.log

**Comment by Aditya-Poulima** [comment]
Getting errors while installing npm packages also:
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path /home/ec2-user/moontimediary_backend/node_modules/swisseph
npm ERR! command failed

**Comment by mivion** [comment]
It looks like permission issue with 'cc' compiler.
